# Disable Spring Cloud Config (assuming you're not using it)
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:

    url: jdbc:h2:tcp://h2database:8091/mem:testdb
    username: root
    password:

    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.H2Dialect

  cloud:
    config:
      enabled: false
  application:
    name: ForumService
# Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# Enable Debug Logging for Eureka
logging:
  level:
    com.netflix.eureka: DEBUG

# Server Port
server:
  port: 8090

